name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: hanizehra
          outputs: |
            output/github-snake.svg
            output/github-snake-dark.svg?palette=github-dark

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update contribution snake"
          file_pattern: output/*.svg
